/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.toystory.client.view;

/**
 *
 * @author simon
 */
public class GameWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameWindow.class.getName());

   /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        // crei i componenti originali nella loro posizione perfetta
        initComponents();
        
        // Trasformiamo i bottoni standard in bottoni Pixel Art azzurri con le nuvole
        applicaStileToyStory(btnGuarda, "GUARDA");
        applicaStileToyStory(btnPrendi, "PRENDI");
        applicaStileToyStory(btnUsa, "USA");
        applicaStileToyStory(btnApri, "APRI");
        applicaStileToyStory(btnChiudi, "CHIUDI");
        applicaStileToyStory(btnParla, "PARLA");
        applicaStileToyStory(btnDai, "DAI");
        applicaStileToyStory(btnSpingi, "SPINGI");
        applicaStileToyStory(btnTira, "TIRA");
        
        // ====================================================================
        // INIZIALIZZAZIONE E TRACCIAMENTO DELLE COORDINATE DELLA STANZA
        // ====================================================================

        // 1. Puliamo il pannello da eventuali vecchi residui grafici
        pnlRappresentazioneStanza.removeAll();

        // 2. Creiamo il visualizzatore adattivo
        com.toystory.client.view.PannelloImmagineAdattiva visualizzatoreStanza = 
                new com.toystory.client.view.PannelloImmagineAdattiva();

        // 3. Lo impostiamo al centro del pannello principale
        pnlRappresentazioneStanza.setLayout(new java.awt.BorderLayout());
        pnlRappresentazioneStanza.add(visualizzatoreStanza, java.awt.BorderLayout.CENTER);

        // 4. Diciamo al visualizzatore di inoltrare i clic a "pnlRappresentazioneStanzaMouseClicked"
        visualizzatoreStanza.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRappresentazioneStanzaMouseClicked(evt);
            }
        });

        // 5. Aggiorniamo la grafica del pannello per renderlo visibile subito
        pnlRappresentazioneStanza.revalidate();
        pnlRappresentazioneStanza.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuperiore = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        lblNomeStanza = new javax.swing.JLabel();
        pnlRappresentazioneStanza = new com.toystory.client.view.PannelloImmagineAdattiva();
        pnlInferiore = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaStoria = new javax.swing.JTextArea();
        pnlPulsantiera = new javax.swing.JPanel();
        pnlVerbi = new javax.swing.JPanel();
        btnDai = new javax.swing.JButton();
        btnPrendi = new javax.swing.JButton();
        btnUsa = new javax.swing.JButton();
        btnApri = new javax.swing.JButton();
        btnGuarda = new javax.swing.JButton();
        btnSpingi = new javax.swing.JButton();
        btnChiudi = new javax.swing.JButton();
        btnParla = new javax.swing.JButton();
        btnTira = new javax.swing.JButton();
        pnlTasche = new javax.swing.JPanel();
        btnSlotInventario1 = new javax.swing.JButton();
        btnSlotInventario2 = new javax.swing.JButton();
        pnlPersonaggio = new javax.swing.JPanel();
        listPersonaggi = new javax.swing.JComboBox<>();
        lblGiocatoreCorrente = new javax.swing.JLabel();
        lblAvatarPersonaggio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSuperiore.setPreferredSize(new java.awt.Dimension(800, 50));
        pnlSuperiore.setLayout(new java.awt.BorderLayout());

        btnMenu.setText("MENU");
        btnMenu.addActionListener(this::btnMenuActionPerformed);
        pnlSuperiore.add(btnMenu, java.awt.BorderLayout.LINE_START);

        lblNomeStanza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeStanza.setText("NOME STANZA ");
        pnlSuperiore.add(lblNomeStanza, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlSuperiore, java.awt.BorderLayout.PAGE_START);

        pnlRappresentazioneStanza.setBackground(new java.awt.Color(153, 153, 153));
        pnlRappresentazioneStanza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRappresentazioneStanzaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlRappresentazioneStanzaLayout = new javax.swing.GroupLayout(pnlRappresentazioneStanza);
        pnlRappresentazioneStanza.setLayout(pnlRappresentazioneStanzaLayout);
        pnlRappresentazioneStanzaLayout.setHorizontalGroup(
            pnlRappresentazioneStanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        pnlRappresentazioneStanzaLayout.setVerticalGroup(
            pnlRappresentazioneStanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        getContentPane().add(pnlRappresentazioneStanza, java.awt.BorderLayout.CENTER);

        pnlInferiore.setPreferredSize(new java.awt.Dimension(800, 150));
        pnlInferiore.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(java.awt.Color.lightGray);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(234, 40));

        txtAreaStoria.setEditable(false);
        txtAreaStoria.setColumns(20);
        txtAreaStoria.setLineWrap(true);
        txtAreaStoria.setRows(5);
        txtAreaStoria.setText("TESTO\n");
        txtAreaStoria.setPreferredSize(new java.awt.Dimension(232, 40));
        jScrollPane1.setViewportView(txtAreaStoria);

        pnlInferiore.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        pnlPulsantiera.setBackground(new java.awt.Color(0, 204, 255));
        pnlPulsantiera.setForeground(new java.awt.Color(0, 0, 102));
        pnlPulsantiera.setLayout(new java.awt.GridLayout(1, 3));

        pnlVerbi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));
        pnlVerbi.setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        btnDai.setText("Dai");
        btnDai.addActionListener(this::btnDaiActionPerformed);
        pnlVerbi.add(btnDai);

        btnPrendi.setText("Prendi");
        pnlVerbi.add(btnPrendi);

        btnUsa.setText("Usa");
        pnlVerbi.add(btnUsa);

        btnApri.setText("Apri");
        pnlVerbi.add(btnApri);

        btnGuarda.setText("Guarda");
        pnlVerbi.add(btnGuarda);

        btnSpingi.setText("Spingi");
        pnlVerbi.add(btnSpingi);

        btnChiudi.setText("Chiudi");
        pnlVerbi.add(btnChiudi);

        btnParla.setText("Parla");
        pnlVerbi.add(btnParla);

        btnTira.setText("Tira");
        pnlVerbi.add(btnTira);

        pnlPulsantiera.add(pnlVerbi);

        pnlTasche.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 50));
        pnlTasche.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        btnSlotInventario1.setText("[Vuoto]");
        btnSlotInventario1.addActionListener(this::btnSlotInventario1ActionPerformed);
        pnlTasche.add(btnSlotInventario1);

        btnSlotInventario2.setText("[Vuoto]");
        pnlTasche.add(btnSlotInventario2);

        pnlPulsantiera.add(pnlTasche);

        pnlPersonaggio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));
        pnlPersonaggio.setLayout(new java.awt.BorderLayout());

        listPersonaggi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listPersonaggi.addActionListener(this::listPersonaggiActionPerformed);
        pnlPersonaggio.add(listPersonaggi, java.awt.BorderLayout.NORTH);

        lblGiocatoreCorrente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGiocatoreCorrente.setText("NOME PERSONAGGIO ATTIVO");
        pnlPersonaggio.add(lblGiocatoreCorrente, java.awt.BorderLayout.SOUTH);

        lblAvatarPersonaggio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatarPersonaggio.setText("immagine");
        pnlPersonaggio.add(lblAvatarPersonaggio, java.awt.BorderLayout.CENTER);

        pnlPulsantiera.add(pnlPersonaggio);

        pnlInferiore.add(pnlPulsantiera, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlInferiore, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnDaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaiActionPerformed

    private void btnSlotInventario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlotInventario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSlotInventario1ActionPerformed

    private void listPersonaggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPersonaggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPersonaggiActionPerformed

    private void pnlRappresentazioneStanzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRappresentazioneStanzaMouseClicked
        // 1. Recupera le coordinate X e Y di dove ha cliccato il mouse rispetto al pannello
        int mouseX = evt.getX();
        int mouseY = evt.getY();
    
        // Stampiamo in console per fare i test e "mappare" le coordinate degli oggetti sullo sfondo
        System.out.println("Hai cliccato nella stanza a coordinate: X = " + mouseX + ", Y = " + mouseY);
    
        /* * 2. Esempio logico di controllo (immagina che il Baule si trovi 
        * in un'area compresa tra X(100-200) e Y(150-250))
        */
        if (mouseX >= 100 && mouseX <= 200 && mouseY >= 150 && mouseY <= 250) {
            txtAreaStoria.setText("Hai cliccato sul Baule di Andy!");
        
         // Qui intercetteremo il verbo memorizzato prima, es:
         // String comando = azioneSelezionata + "|baule";
         // gameClient.inviaComando(comando);
        }
    }//GEN-LAST:event_pnlRappresentazioneStanzaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameWindow().setVisible(true));
    }
private void applicaStileToyStory(javax.swing.JButton bottone, String verbo) {
    // Genera l'immagine standard e quella per quando il mouse ci passa sopra (Rollover/Hover)
    bottone.setIcon(PixelButtonGenerator.createToyStoryButton(verbo, false));
    bottone.setRolloverIcon(PixelButtonGenerator.createToyStoryButton(verbo, true));
    bottone.setPressedIcon(PixelButtonGenerator.createToyStoryButton(verbo, true));

    // Rimuove la vecchia grafica grigia standard delle finestre
    bottone.setBorderPainted(false);
    bottone.setContentAreaFilled(false);
    bottone.setFocusPainted(false);
    
    // Rimuove il vecchio testo testuale, visto che ora la parola è disegnata dentro l'immagine!
    bottone.setText(""); 
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApri;
    private javax.swing.JButton btnChiudi;
    private javax.swing.JButton btnDai;
    private javax.swing.JButton btnGuarda;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnParla;
    private javax.swing.JButton btnPrendi;
    private javax.swing.JButton btnSlotInventario1;
    private javax.swing.JButton btnSlotInventario2;
    private javax.swing.JButton btnSpingi;
    private javax.swing.JButton btnTira;
    private javax.swing.JButton btnUsa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvatarPersonaggio;
    private javax.swing.JLabel lblGiocatoreCorrente;
    private javax.swing.JLabel lblNomeStanza;
    private javax.swing.JComboBox<String> listPersonaggi;
    private javax.swing.JPanel pnlInferiore;
    private javax.swing.JPanel pnlPersonaggio;
    private javax.swing.JPanel pnlPulsantiera;
    private javax.swing.JPanel pnlRappresentazioneStanza;
    private javax.swing.JPanel pnlSuperiore;
    private javax.swing.JPanel pnlTasche;
    private javax.swing.JPanel pnlVerbi;
    private javax.swing.JTextArea txtAreaStoria;
    // End of variables declaration//GEN-END:variables
}
