package com.toystory.client.view;

import com.toystory.client.view.components.PixelButtonGenerator;



/**
 * Finestra principale dell'applicazione client.
 * <p>
 * Rappresenta la Vista (View) nel pattern MVC. Gestisce l'intera interfaccia grafica,
 * il rendering degli elementi di gioco e l'invio degli input utente al {@link GameWindowController}.
 * </p>
 * <p>
 * Questa classe utilizza componenti Swing personalizzati per mantenere lo stile 
 * visivo del gioco e non contiene logica di business, limitandosi a eseguire 
 * comandi grafici ricevuti dal sistema.
 * </p>
 * 
 * @author simon
 */
public class GameWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameWindow.class.getName());
    private GameWindowController controller;
    
    

    /**
     * Inizializza la finestra di gioco, applica gli stili grafici ai componenti
     * e avvia il flusso di connessione tramite il controller.
     */
    public GameWindow() {
        initComponents();
        // --- 1. Configurazione Font e Testi ---
        txtAreaStoria.setPreferredSize(null);
        txtAreaStoria.setFont(new java.awt.Font("Verdana", java.awt.Font.BOLD, 12));
        txtAreaStoria.setForeground(java.awt.Color.WHITE);
        lblNomeStanza.setFont(new java.awt.Font("Arial Black", java.awt.Font.BOLD, 16));
        lblNomeStanza.setForeground(java.awt.Color.RED);         
        
        // --- 2. Inizializzazione Stili Componenti (via PixelButtonGenerator) ---
        PixelButtonGenerator.impostaIconaAvatar(btnSelezionaBuzz, "/icone_buzz.png");
        PixelButtonGenerator.impostaIconaAvatar(btnSelezionaWoody, "/icone_woody.png");
        PixelButtonGenerator.impostaIconaAvatar(btnSelezionaJessie, "/icone_jessie.png");
        
        // Stile Bottoni Azioni
        PixelButtonGenerator.applicaStileToyStory(btnGuarda, "GUARDA");
        PixelButtonGenerator.applicaStileToyStory(btnPrendi, "PRENDI");
        PixelButtonGenerator.applicaStileToyStory(btnUsa, "USA");
        PixelButtonGenerator.applicaStileToyStory(btnParla, "PARLA");
        PixelButtonGenerator.applicaStileToyStory(btnVai, "VAI");
        
        // Stile Sfondi Pannelli
        PixelButtonGenerator.applicaSfondoBottoni(pnlVerbi);
        PixelButtonGenerator.applicaSfondoPersonaggi(pnlPersonaggio);
        PixelButtonGenerator.applicaSfondoTasche(pnlTasche);
        
        // --- 3. Configurazione Inventario ---
        btnSlotInventario1.setContentAreaFilled(false);
        btnSlotInventario1.setOpaque(false);
        btnSlotInventario1.setBorderPainted(false);
        
        btnSlotInventario2.setContentAreaFilled(false);
        btnSlotInventario2.setOpaque(false);
        btnSlotInventario2.setBorderPainted(false);
        
        lblIconaAbilita.setOpaque(false);
        
        // Selezione di default
        btnSelezionaWoody.setSelected(true); 
        aggiornaBordiPersonaggi(null); 
        
        // --- 4. Avvio Controller ---
        this.controller = new GameWindowController(this);
        java.awt.EventQueue.invokeLater(() -> controller.avviaFlussoIniziale());
        
        // --- 5. Layout e Dimensioni ---
        
        // 5.1. Diamo al pannello le proporzioni esatte 
        pnlRappresentazioneStanza.setPreferredSize(new java.awt.Dimension(712, 374));
        
        // 5.2. Blocchiamo la finestra in modo che il giocatore non possa sformarla
        this.setResizable(false); 
        
        // 5.3. Diciamo alla finestra di riadattare la sua grandezza generale 
        // in base alle nuove dimensioni perfette del pannello
        this.pack();
        
        // 5.4. Centriamo la finestra perfettamente al centro dello schermo
        this.setLocationRelativeTo(null);
        
        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 70));
          
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlSuperiore = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        lblNomeStanza = new javax.swing.JLabel();
        pnlRappresentazioneStanza = new com.toystory.client.view.components.PannelloImmagineAdattiva();
        pnlInferiore = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaStoria = new javax.swing.JTextArea();
        pnlPulsantiera = new javax.swing.JPanel();
        pnlVerbi = new javax.swing.JPanel();
        btnPrendi = new javax.swing.JButton();
        btnUsa = new javax.swing.JButton();
        btnGuarda = new javax.swing.JButton();
        btnParla = new javax.swing.JButton();
        btnVai = new javax.swing.JButton();
        pnlTasche = new javax.swing.JPanel();
        btnSlotInventario1 = new javax.swing.JButton();
        lblIconaAbilita = new javax.swing.JLabel();
        btnSlotInventario2 = new javax.swing.JButton();
        pnlPersonaggio = new javax.swing.JPanel();
        labelAvatar = new javax.swing.JLabel();
        cambiaIconaAvatar = new javax.swing.JPanel();
        Woody = new javax.swing.JPanel();
        btnSelezionaWoody = new javax.swing.JToggleButton();
        Jessie = new javax.swing.JPanel();
        btnSelezionaJessie = new javax.swing.JToggleButton();
        Buzz = new javax.swing.JPanel();
        btnSelezionaBuzz = new javax.swing.JToggleButton();
        lblGiocatoreCorrente = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSuperiore.setMinimumSize(new java.awt.Dimension(162, 13));
        pnlSuperiore.setPreferredSize(new java.awt.Dimension(800, 27));
        pnlSuperiore.setLayout(new java.awt.BorderLayout());

        btnMenu.setText("MENU");
        btnMenu.addActionListener(this::btnMenuActionPerformed);
        pnlSuperiore.add(btnMenu, java.awt.BorderLayout.LINE_START);

        lblNomeStanza.setBackground(new java.awt.Color(51, 51, 0));
        lblNomeStanza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeStanza.setText("NOME STANZA ");
        lblNomeStanza.setPreferredSize(new java.awt.Dimension(86, 10));
        pnlSuperiore.add(lblNomeStanza, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlSuperiore, java.awt.BorderLayout.PAGE_START);

        pnlRappresentazioneStanza.setBackground(new java.awt.Color(153, 153, 153));
        pnlRappresentazioneStanza.setPreferredSize(new java.awt.Dimension(762, 233));
        pnlRappresentazioneStanza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRappresentazioneStanzaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlRappresentazioneStanzaLayout = new javax.swing.GroupLayout(pnlRappresentazioneStanza);
        pnlRappresentazioneStanza.setLayout(pnlRappresentazioneStanzaLayout);
        pnlRappresentazioneStanzaLayout.setHorizontalGroup(
            pnlRappresentazioneStanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        pnlRappresentazioneStanzaLayout.setVerticalGroup(
            pnlRappresentazioneStanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        getContentPane().add(pnlRappresentazioneStanza, java.awt.BorderLayout.CENTER);

        pnlInferiore.setPreferredSize(new java.awt.Dimension(800, 166));
        pnlInferiore.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(234, 55));

        txtAreaStoria.setEditable(false);
        txtAreaStoria.setBackground(new java.awt.Color(51, 153, 255));
        txtAreaStoria.setColumns(20);
        txtAreaStoria.setLineWrap(true);
        txtAreaStoria.setRows(5);
        txtAreaStoria.setWrapStyleWord(true);
        txtAreaStoria.setPreferredSize(new java.awt.Dimension(232, 70));
        jScrollPane1.setViewportView(txtAreaStoria);

        pnlInferiore.add(jScrollPane1, java.awt.BorderLayout.NORTH);

        pnlPulsantiera.setLayout(new java.awt.GridLayout(1, 3));

        pnlVerbi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));
        pnlVerbi.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        btnPrendi.setText("Prendi");
        btnPrendi.addActionListener(this::btnPrendiActionPerformed);
        pnlVerbi.add(btnPrendi);

        btnUsa.setText("Usa");
        btnUsa.addActionListener(this::btnUsaActionPerformed);
        pnlVerbi.add(btnUsa);

        btnGuarda.setText("Guarda");
        btnGuarda.addActionListener(this::btnGuardaActionPerformed);
        pnlVerbi.add(btnGuarda);

        btnParla.setText("Parla");
        btnParla.addActionListener(this::btnParlaActionPerformed);
        pnlVerbi.add(btnParla);

        btnVai.setText("Vai");
        btnVai.addActionListener(this::btnVaiActionPerformed);
        pnlVerbi.add(btnVai);

        pnlPulsantiera.add(pnlVerbi);

        pnlTasche.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 50));
        pnlTasche.setMaximumSize(new java.awt.Dimension(32767, 30000));
        pnlTasche.setLayout(new java.awt.GridLayout(2, 2, 0, 10));
        pnlTasche.add(btnSlotInventario1);

        lblIconaAbilita.setPreferredSize(new java.awt.Dimension(100, 100));
        pnlTasche.add(lblIconaAbilita);
        pnlTasche.add(btnSlotInventario2);

        pnlPulsantiera.add(pnlTasche);

        pnlPersonaggio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));
        pnlPersonaggio.setLayout(new java.awt.BorderLayout());

        labelAvatar.setEnabled(false);
        pnlPersonaggio.add(labelAvatar, java.awt.BorderLayout.CENTER);

        cambiaIconaAvatar.setOpaque(false);
        cambiaIconaAvatar.setPreferredSize(new java.awt.Dimension(208, 80));
        cambiaIconaAvatar.setLayout(new java.awt.GridLayout(1, 3));

        Woody.setOpaque(false);

        buttonGroup1.add(btnSelezionaWoody);
        btnSelezionaWoody.setText("jToggleButton2");
        btnSelezionaWoody.setPreferredSize(new java.awt.Dimension(75, 75));
        btnSelezionaWoody.addActionListener(this::btnSelezionaWoodyActionPerformed);
        Woody.add(btnSelezionaWoody);

        cambiaIconaAvatar.add(Woody);

        Jessie.setOpaque(false);

        buttonGroup1.add(btnSelezionaJessie);
        btnSelezionaJessie.setText("jToggleButton2");
        btnSelezionaJessie.setPreferredSize(new java.awt.Dimension(75, 75));
        btnSelezionaJessie.addActionListener(this::btnSelezionaJessieActionPerformed);
        Jessie.add(btnSelezionaJessie);

        cambiaIconaAvatar.add(Jessie);

        Buzz.setOpaque(false);

        buttonGroup1.add(btnSelezionaBuzz);
        btnSelezionaBuzz.setText("jToggleButton2");
        btnSelezionaBuzz.setPreferredSize(new java.awt.Dimension(75, 75));
        btnSelezionaBuzz.addActionListener(this::btnSelezionaBuzzActionPerformed);
        Buzz.add(btnSelezionaBuzz);

        cambiaIconaAvatar.add(Buzz);

        pnlPersonaggio.add(cambiaIconaAvatar, java.awt.BorderLayout.PAGE_START);

        lblGiocatoreCorrente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPersonaggio.add(lblGiocatoreCorrente, java.awt.BorderLayout.SOUTH);

        pnlPulsantiera.add(pnlPersonaggio);

        pnlInferiore.add(pnlPulsantiera, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlInferiore, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
       controller.tornaAlMenu();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void pnlRappresentazioneStanzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRappresentazioneStanzaMouseClicked
          controller.elaboraClickScenario(evt.getX(), evt.getY(), pnlRappresentazioneStanza.getWidth(), pnlRappresentazioneStanza.getHeight());
                                             
     
    }//GEN-LAST:event_pnlRappresentazioneStanzaMouseClicked

    private void btnGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaActionPerformed
        controller.cambiaAzione("GUARDA");
    }//GEN-LAST:event_btnGuardaActionPerformed

    private void btnSelezionaWoodyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelezionaWoodyActionPerformed
        controller.selezionaPersonaggio("Woody");
    }//GEN-LAST:event_btnSelezionaWoodyActionPerformed

    private void btnSelezionaBuzzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelezionaBuzzActionPerformed
      controller.selezionaPersonaggio("Buzz");
    }//GEN-LAST:event_btnSelezionaBuzzActionPerformed

    private void btnSelezionaJessieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelezionaJessieActionPerformed
        controller.selezionaPersonaggio("Jessie");
    }//GEN-LAST:event_btnSelezionaJessieActionPerformed

    private void btnPrendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrendiActionPerformed
        controller.cambiaAzione("PRENDI");
    }//GEN-LAST:event_btnPrendiActionPerformed

    private void btnUsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsaActionPerformed
       controller.cambiaAzione("USA");
    }//GEN-LAST:event_btnUsaActionPerformed

    private void btnVaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaiActionPerformed
       controller.cambiaAzione("VAI");
    }//GEN-LAST:event_btnVaiActionPerformed

    private void btnParlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParlaActionPerformed
        controller.cambiaAzione("PARLA");
    }//GEN-LAST:event_btnParlaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameWindow());
    }
    
    // =============================================================================
    // METODI PONTE (Richiesti dal GUIHandler)
    // =============================================================================

    /**
     * Aggiunge una riga di testo nel registro degli eventi (log) della storia.
     * @param testo Il messaggio da visualizzare.
     */
    public void scriviNelLog(String testo) {
        txtAreaStoria.append(testo + "\n");
        txtAreaStoria.setCaretPosition(txtAreaStoria.getDocument().getLength());
    }

    /**
     * Aggiorna il nome della stanza visualizzato nell'header.
     * @param nomeStanza Il nome della nuova stanza.
     */
    public void aggiornaNomeStanza(String nomeStanza) {
        lblNomeStanza.setText(nomeStanza.toUpperCase());
    }


    /**
     * Aggiorna l'immagine di sfondo del pannello di gioco.
     * @param percorsoImmagine Percorso del file immagine.
     */
    public void impostaSfondo(String percorsoImmagine) {
        if (percorsoImmagine != null && !percorsoImmagine.isEmpty()) {
            ((com.toystory.client.view.components.PannelloImmagineAdattiva) pnlRappresentazioneStanza).cambiaImmagine(percorsoImmagine);
        }
    }

    /**
     * Gestisce l'aggiornamento dello slot abilità.
     * @param nomeAbilita Il nome testuale (es. "Lazo", "Laser" o "Nessuna")
     * @param icona Il percorso dell'immagine inviato dal server
     */
    public void aggiornaSlotAbilita(String nomeAbilita, String icona) {
        scriviNelLog("[Notifica Gioco]: Abilità attiva - " + nomeAbilita);
        
        // Se il server ci dice che c'è un'icona valida (non è "vuoto")
        if (icona != null && !icona.isEmpty() && !icona.equals("vuoto")) {
            try {
                java.net.URL imgURL = getClass().getResource(icona);
                if (imgURL != null) {
                    lblIconaAbilita.setIcon(PixelButtonGenerator.ridimensionaIcona(imgURL, 50, 50));
                } else {
                    System.err.println("[GUI] Immagine abilità non trovata: " + icona);
                    lblIconaAbilita.setIcon(null);
                    lblIconaAbilita.setText(nomeAbilita); // Fallback: mostra il testo
                }
            } catch (Exception e) {
                System.err.println("[GUI] Errore caricamento icona abilità: " + e.getMessage());
            }
        } else {
            // Se il personaggio non ha abilità (es. Woody all'inizio del gioco)
            lblIconaAbilita.setIcon(null); // Rimuove eventuali vecchie immagini
            lblIconaAbilita.setText("");
        }
    }


    /**
    * Aggiorna visivamente i bordi dei bottoni di selezione personaggio (rosso/verde),
    * riflettendo il personaggio attualmente confermato dal server tramite il token
    * PERSONAGGIO_ATTIVO. Non riflette mai uno stato di selezione locale
    * 
    * @param nomeAttivo Il nome del personaggio attualmente controllato da questo client,
    *                    o null se non ancora noto (es. all'avvio, prima della sincronizzazione).
    */
    public void aggiornaBordiPersonaggi(String nomeAttivo) {
        btnSelezionaWoody.setBorder(javax.swing.BorderFactory.createLineBorder(
            "Woody".equalsIgnoreCase(nomeAttivo) ? java.awt.Color.GREEN : java.awt.Color.RED, 3));

        boolean buzzAttivo = nomeAttivo != null &&
            (nomeAttivo.equalsIgnoreCase("Buzz") || nomeAttivo.equalsIgnoreCase("Buzz Lightyear"));
        btnSelezionaBuzz.setBorder(javax.swing.BorderFactory.createLineBorder(
            buzzAttivo ? java.awt.Color.GREEN : java.awt.Color.RED, 3));

        btnSelezionaJessie.setBorder(javax.swing.BorderFactory.createLineBorder(
            "Jessie".equalsIgnoreCase(nomeAttivo) ? java.awt.Color.GREEN : java.awt.Color.RED, 3));
    }
    
    /**
     * Aggiunge un oggetto grafico all'inventario se vi è spazio disponibile.
     * @param nomeOggetto Nome dell'oggetto.
     * @param nomeFile Percorso dell'icona.
     */
    public void aggiungiAllInventario(String nomeOggetto, String nomeFile) {
        // 1. Prepariamo l'icona usando la nostra utility centralizzata
        java.net.URL imgURL = getClass().getResource("/" + nomeFile);
        javax.swing.ImageIcon icona = PixelButtonGenerator.ridimensionaIcona(imgURL, 40, 40);

        // 2. Inseriamo negli slot
        if (btnSlotInventario1.getIcon() == null) {
            btnSlotInventario1.setIcon(icona);
            btnSlotInventario1.setText(""); 
        } else if (btnSlotInventario2.getIcon() == null) {
            btnSlotInventario2.setIcon(icona);
            btnSlotInventario2.setText("");
        } else {
            scriviNelLog("[Sistema - GUI]: Le tue tasche sono piene!");
        }
    }
    
    /**
     * Rimuove tutti gli oggetti dall'inventario grafico.
     */
    public void svuotaInventario() {
        // Togliamo le icone
        btnSlotInventario1.setIcon(null);
        btnSlotInventario1.setText("");
        
        btnSlotInventario2.setIcon(null);
        btnSlotInventario2.setText("");
    }
    
    /**
     * Stampa un testo nel registro con un effetto di pausa automatizzata tra le frasi.
     * @param testoCompleto Testo contenente i marcatori.
     */
    public void stampaTestoConPausa(String testoCompleto) {
        // 1. Traduciamo il nostro codice di rete <BR> in un vero e proprio "a capo" per la grafica
        testoCompleto = testoCompleto.replace("<BR>", "\n");

        if (!testoCompleto.contains("<PAUSA>")) {
            txtAreaStoria.append(testoCompleto + "\n");
            txtAreaStoria.setCaretPosition(txtAreaStoria.getDocument().getLength());
            return;
        }

        // Dividiamo il testo usando il nostro segnalibro temporale
        String[] battute = testoCompleto.split("<PAUSA>");
        
        // Stampiamo subito la prima frase senza aspettare
        txtAreaStoria.append(battute[0] + "\n");
        txtAreaStoria.setCaretPosition(txtAreaStoria.getDocument().getLength());
        
        // Timer per stampare le restanti frasi ogni 1.5 secondi
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            // PARTIAMO DA 1 (perché la frase 0 l'abbiamo appena stampata)
            int indice = 1; 

            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (indice < battute.length) {
                    txtAreaStoria.append(battute[indice] + "\n");
                    txtAreaStoria.setCaretPosition(txtAreaStoria.getDocument().getLength());
                    indice++;
                } else {
                    ((javax.swing.Timer) e.getSource()).stop();
                }
            }
        });

        timer.setInitialDelay(1500);
        timer.start();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buzz;
    private javax.swing.JPanel Jessie;
    private javax.swing.JPanel Woody;
    private javax.swing.JButton btnGuarda;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnParla;
    private javax.swing.JButton btnPrendi;
    private javax.swing.JToggleButton btnSelezionaBuzz;
    private javax.swing.JToggleButton btnSelezionaJessie;
    private javax.swing.JToggleButton btnSelezionaWoody;
    private javax.swing.JButton btnSlotInventario1;
    private javax.swing.JButton btnSlotInventario2;
    private javax.swing.JButton btnUsa;
    private javax.swing.JButton btnVai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cambiaIconaAvatar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelAvatar;
    private javax.swing.JLabel lblGiocatoreCorrente;
    private javax.swing.JLabel lblIconaAbilita;
    private javax.swing.JLabel lblNomeStanza;
    private javax.swing.JPanel pnlInferiore;
    private javax.swing.JPanel pnlPersonaggio;
    private javax.swing.JPanel pnlPulsantiera;
    private javax.swing.JPanel pnlRappresentazioneStanza;
    private javax.swing.JPanel pnlSuperiore;
    private javax.swing.JPanel pnlTasche;
    private javax.swing.JPanel pnlVerbi;
    private javax.swing.JTextArea txtAreaStoria;
    // End of variables declaration//GEN-END:variables
}
